### ISSUE TITLE
Running on localhost:1337 always returns the error "Couldn't resolve host. The given remote host was not resolved."

### ISSUE THREAD

**Issue by jfrumar** [chriso/curlrequest#18]
I'm on OSX 10.9.3 and whenever I run a script that hits localhost:1337, I receive this error in my callback:

_Couldn't resolve host. The given remote host was not resolved._

If I pass in a function as the options.process parameter, it is called with the correct response from the server.

Regardless of whether the server returns a status of 400 or 200, I receive the same error message.

I have tried using http://127.0.0.1:1337 and http://localhost:1337 and they both trigger that error message.

**Comment by Hoya** [comment]
I'm experiencing this issue with OSX 10.13.6.

The server is returning 200 along with the correct data but the error variable on the callback is always "Couldn't resolve host. The given remote host was not resolved."
