### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by thomasmodeneis** [chriso/curlrequest#20]
Hi chriso,
I like your lib, how can I use to for file upload ?

Like: curl -i -F name=test -F filedata=@localfile.jpg http://example.org/upload
Thank you

**Comment by Sk8er22** [comment]
Hi!

i need this curl 
curl -X POST -H "Content-Type: multipart/form-data" -F "file=@./filepath.jpg" -F"name_discoteca=Testing" -F "id_discoteca=19" -F "ispublic=1" -F "id_user=asd" WEBURL << this works...


but i try with your library a lot of combinations using --form & --data with " ' ; & , for join all the parameters but not work

Can you explain me pls? i need POST send a file and 4 parameters

**Comment by chriso** [comment]
```javascript

```

**Comment by Sk8er22** [comment]
nope, form with & and = with or without double quotes doesn't works :(

**Comment by chriso** [comment]
When you say doesn't work, what's actually happening? Are you getting an error, is nothing happening, or is the request being made but not with the file appended?

A few things to try:

- try using an absolute path to your `@./filepath.jpg`, e.g. `@/full/path/to/filepath.jpg`
- try printing out the curl args that are used (see the example [here](https://github.com/chriso/curlrequest/issues/20#issuecomment-53978223). Then try running the exact same command in the same directory as your file

**Comment by Sk8er22** [comment]
When i do what you said, the php doesn't got the file but got the parameters... the only way that works is like i said with -F i add behind url comand all my -F -F -F -F this can works?

i get this printing command:

now i have this in log : curl --silent --show-error --no-buffer --url http:url.com -F "file=@/Users/user/Downloads/WiPho-master/public/previews/dscn0271.jpg" -F "name_discoteca=Testing" -F "id_discoteca=19" -F "ispublic=1" -F "id_user=ads" --request POST --location --max-redirs 3 --header Accept: */* --header Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3 --header Accept-Language: en-US,en;q=0.8

if i copy and paste it works! but on the JS dosen't do anything T_T

**Comment by Sk8er22** [comment]
i have this error node_modules/curlrequest/index.js:223
        options.header.push(key + ': ' + headers[key]);

**Comment by chriso** [comment]
Yeah it looks like the reason that the file isn't making it is because it's missing the `Content-Type: multipart/form-data` header.

What version of curlrequest are you using?

Try passing in `headers: {'content-type': 'multipart/form-data'}` instead.

**Comment by Sk8er22** [comment]
works that header, but now i miss the parameters xD

[ '--silent',
  '--show-error',
  '--no-buffer',
  '--url',
  'http://URL',
  '--data',
 'id_user=123&name_discoteca=Testing&id_discoteca=19&ispublic=1&file=@/Users/user/Downloads/WiPho-master/public/previews/dscn0278.jpg',
  '--request',
  'POST',
  '--location',
  '--max-redirs',
  3,
  '--header',
  'Accept: */*',
  '--header',
  'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3',
  '--header',
  'Accept-Language: en-US,en;q=0.8',
  '--header',
  'Content-Type: multipart/form-data',
  '--user-agent',
  'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)' ]

And if i don't sent the headers detects the parameters but not the file... :S

File not recibed
[ '--silent',
  '--show-error',
  '--no-buffer',
  '--url',
  'http://URL',
  '--data',
  
'id_user=123&name_discoteca=Testing&id_discoteca=19&ispublic=1&file=@/Users/user/Downloads/WiPho-master/public/previews/dscn0278.jpg',
  '--request',
  'POST',
  '--location',
  '--max-redirs',
  3,
  '--header',
  'Accept: */*',
  '--header',
  'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3',
  '--header',
  'Accept-Language: en-US,en;q=0.8',
  '--user-agent',
  'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.861.0 Safari/535.2' ]

**Comment by chriso** [comment]
Yeah you'll need to use `form` rather than `data`.

Try passing in an array:

```
form: ['file=@./filepath.jpg', 'name_discoteca=Testing', 'id_discoteca=19', 'ispublic=1', 'id_user=asd']
```

**Comment by Sk8er22** [comment]
on curl call --form [object Object] if i set an array

and if i set everything in a line with & or ; joining them doesn't work, miss parameters... the call have to call for each object a -F ... something crazy... i don't know why

i try calling a form for each one but just write the last one, it's possible than write one for each?

**Comment by chriso** [comment]
Ok I've fixed the issue in version `0.5.2`.  Update **curlrequest** and then try again with passing the form vars via an array.

**Comment by Sk8er22** [comment]
that's true, anyway u join the array with & and not work... just take the first parameter... --form i guess than need a -form for each one not join all parameters =/ 

curl --silent --show-error --no-buffer --url http://asd/asd.php --form file=@/Users/asd/Downloads/WiPho-master/public/previews/dscn0348.jpg&id_user=123&name_discoteca=Testing&id_discoteca=19&ispublic=1 --request POST --location --max-redirs 3 --header Accept: */* --header Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3 --header Accept-Language: en-US,en;q=0.8 --header Content-Type: multipart/form-data --user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_6) AppleWebKit/534.22 (KHTML, like Gecko) Chrome/11.0.683.0 Safari/534.22

**Comment by chriso** [comment]
I you upgrade to `0.5.2` and then pass in the form vars like so:

```
var options = {
    method: 'POST',
    headers: {'Content-Type': 'multipart/form-data'},
    form: [
        'file=@./filepath.jpg',
        'name_discoteca=Testing',
        'id_discoteca=19',
        'ispublic=1',
        'id_user=asd'
    ],
    url: 'http://example.org/upload'
};

curl.request(options, function (err, data) {
    ....
});
```

It will correctly split them up as separate args to curl:

```
curl ... --form "file=@./filepath.jpg" --form "name_discoteca=Testing" --form "id_discoteca=19" ...
```

**Comment by Sk8er22** [comment]
I love you! i'm too tard! hahahha I owe you a beers... WORKS

**Comment by chriso** [comment]
Great :smile:

**Comment by muton** [comment]
@chriso Thanks for doing this library, would be handy to see the form array syntax in the readme - took me a while to track it down here!
