### ISSUE TITLE
How do i include parameters to be passed while making the request?

### ISSUE THREAD

**Issue by saru95** [chriso/curlrequest#25]
as in request parameters .

**Comment by chriso** [comment]
Use the `data` option.

If you want to make a POST request with content type `application/x-www-form-urlencoded`:

```javascript
curl.request({
    url: 'http://example.com/',
    data: {'foo': 'bar'}
}, function (err, response) {

});
```

If you want to make a GET request, then either use `curl.request('http://example.com/?foo=bar', ...)`, or the long form version:

```javascript
curl.request({
    get: true,
    url: 'http://example.com/',
    data: {'foo': 'bar'},
}, function (err, response) {

});
```
