### ISSUE TITLE
curl request call callback function before get all stdout stream.

### ISSUE THREAD

**Issue by floodZero** [chriso/curlrequest#26]
Hi, chriso.
I'm gavin of korea. (So, you could feel odd in my English.)

I found some issue on rapid request situation.
When curlrequest.request called rapidly, callback's data argument get "" string often.
With no error object and no stdrerr stream.
Also i checked packets, and it's good. there's no problem.

And I solved this issue, I think.

I changed bind of "exit" event to "close". And "" string output disappeared.

```javascript
//Handle curl exit
curl.on('exit', function (code) {
  try {
    err = code;

to

curl.on('close', function (code) {
  try {
    err = code;
```

According to this [API doc](https://nodejs.org/api/child_process.html#child_process_event_exit), 
"exit" event can be emitted before stdout stream flushed.

How you think about this modification?

**Comment by chriso** [comment]
Thanks, it sounds like it should be `close` rather than `exit`. I'd be happy to accept a PR with the fix :smile:

**Comment by floodZero** [comment]
OK, I requested PR from my fork.
Thank you. :)
