### ISSUE TITLE
On heroku its failing

### ISSUE THREAD

**Issue by pulkitnandan** [chriso/curlrequest#31]
I have very simple app in sailsjs which uses curl request  for simple get request but fails with following error on heroku, is this heroku or some issue with this

[36m2015-09-16T21:07:02.031430+00:00 app[web.1]:[0m Check for new additions
[36m2015-09-16T21:07:21.671439+00:00 app[web.1]:[0m Total committees found are 30
[36m2015-09-16T21:07:21.671445+00:00 app[web.1]:[0m Processing Them
[36m2015-09-16T21:07:21.671446+00:00 app[web.1]:[0m
[36m2015-09-16T21:07:21.872619+00:00 app[web.1]:[0m /app/node_modules/curlrequest/index.js:260
[36m2015-09-16T21:07:21.872624+00:00 app[web.1]:[0m         curl.stdout.on('data', function (data) {
[36m2015-09-16T21:07:21.872626+00:00 app[web.1]:[0m                    ^
[36m2015-09-16T21:07:21.872627+00:00 app[web.1]:[0m TypeError: Cannot read property 'on' of undefined
[36m2015-09-16T21:07:21.872628+00:00 app[web.1]:[0m     at /app/node_modules/curlrequest/index.js:260:20
[36m2015-09-16T21:07:21.872630+00:00 app[web.1]:[0m     at module.exports (/app/node_modules/curlrequest/spawn.js:19:9)
[36m2015-09-16T21:07:21.872631+00:00 app[web.1]:[0m     at Object.exports.request (/app/node_modules/curlrequest/index.js:257:17)
[36m2015-09-16T21:07:21.872632+00:00 app[web.1]:[0m     at /app/crontab/committees.js:27:22
[36m2015-09-16T21:07:21.872634+00:00 app[web.1]:[0m     at wrapper (/app/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
[36m2015-09-16T21:07:21.872635+00:00 app[web.1]:[0m     at applyInOriginalCtx (/app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
[36m2015-09-16T21:07:21.872637+00:00 app[web.1]:[0m     at wrappedCallback (/app/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
[36m2015-09-16T21:07:21.872638+00:00 app[web.1]:[0m     at callback.success (/app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
[36m2015-09-16T21:07:21.872639+00:00 app[web.1]:[0m     at _switch (/app/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
[36m2015-09-16T21:07:21.872640+00:00 app[web.1]:[0m     at returnResults (/app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:392:9)
[36m2015-09-16T21:07:21.872641+00:00 app[web.1]:[0m     at /app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:272:16
[36m2015-09-16T21:07:21.872642+00:00 app[web.1]:[0m     at /app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
[36m2015-09-16T21:07:21.872644+00:00 app[web.1]:[0m     at /app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
[36m2015-09-16T21:07:21.872646+00:00 app[web.1]:[0m     at Object.async.forEachOf.async.eachOf (/app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:227:20)
[36m2015-09-16T21:07:21.872647+00:00 app[web.1]:[0m     at Object.async.forEach.async.each (/app/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
[36m2015-09-16T21:07:21.872648+00:00 app[web.1]:[0m     at /app/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:433:11
[36m2015-09-16T21:07:21.894708+00:00 app[web.1]:[0m Error waiting for process to terminate: No child processes

**Comment by chriso** [comment]
What version of node are you using? Can you provide some example code?

**Comment by pulkitnandan** [comment]
its been a issue related to heroku which donot accepts mannual npm install after doing heroku run bash.
